version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/usr/src/app
      - ./api/app:/usr/src/app:ro
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
